# Use Node.js LTS version as base image
FROM node:20-alpine

ARG VITE_SERVER_BASE_URL
ENV VITE_SERVER_BASE_URL=$VITE_SERVER_BASE_URL

ARG VITE_AWS_SECRET_KEY
ENV VITE_AWS_SECRET_KEY=$VITE_AWS_SECRET_KEY

ARG VITE_AWS_ACCESS_KEY
ENV VITE_AWS_ACCESS_KEY=$VITE_AWS_ACCESS_KEY

ARG VITE_AWS_REGION
ENV VITE_AWS_REGION=$VITE_AWS_REGION

ARG VITE_AWS_BUCKET_NAME
ENV VITE_AWS_BUCKET_NAME=$VITE_AWS_BUCKET_NAME

ARG VITE_AWS_BUCKET_BASE_URL
ENV VITE_AWS_BUCKET_BASE_URL=$VITE_AWS_BUCKET_BASE_URL

ARG VITE_MAPBOX_PUBLIC_KEY
ENV VITE_MAPBOX_PUBLIC_KEY=$VITE_MAPBOX_PUBLIC_KEY

ARG VITE_STRAVA_CLIENT_ID
ENV VITE_STRAVA_CLIENT_ID=$VITE_STRAVA_CLIENT_ID

ARG VITE_GOOGLE_CLIENT_ID
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID

ARG VITE_PUBLIC_POSTHOG_KEY
ENV VITE_PUBLIC_POSTHOG_KEY=$VITE_PUBLIC_POSTHOG_KEY

ARG VITE_PUBLIC_POSTHOG_HOST
ENV VITE_PUBLIC_POSTHOG_HOST=$VITE_PUBLIC_POSTHOG_HOST


# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN yarn install

# Copy source code
COPY . .

# Remove .env file if it exists
RUN rm -f .env

# Install curl
RUN apk add --no-cache curl

# Build the application
RUN yarn build

# Expose port
EXPOSE 3000

# Start the application
CMD ["yarn", "start"]
